spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
